#!/usr/bin/env bash
# Cross-reference this project's assembler against GNU as.
#
# asm/test/differential compares one CompCert fixture per target against a
# committed GNU oracle. That establishes agreement on 24 encoding forms and
# nothing else, because 24 forms is all the fixtures contain. This corpus is
# the same claim over inputs the fixtures do not reach, and it grows on its own:
# every entry test/snippets can assemble becomes a case here.
#
# The inputs are *generated from the AST corpus*, not hand-written. One AST
# yields our bytes, the hexdump baseline in test/snippets, and the .s file GNU
# as reads - all through the same canonical printer. A disagreement is then
# attributable to the two encoders, because the input is not in question. Hand
# writing the .s would have reintroduced exactly the second description this
# whole exercise removes.
#
# Two modes, and the split is asm/Makefile's §12 policy rather than a
# convenience (see the comment above asm-fixtures-check):
#
#   --regen   needs the four cross binutils. Rebuilds the corpus and its
#             manifest. Runs from `make asm-gas-xref-regen`, downstream of
#             asm-cross-setup.
#   --check   hashes the committed corpus and nothing else. No toolchain, no
#             emulator, so `make asm-test` acquires neither.
#
# The normalizations are asm-fixture-oracle.sh's, for its reasons: absolute
# paths and the object filename are stripped so the artifacts do not encode
# where this checkout lives, and .text is dumped in **memory order**, because
# objdump prints ARM and AArch64 instruction *words* and comparing word order
# against a byte-oriented encoder would appear to work and be wrong.
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
# shellcheck source=target-matrix.sh
. "$SCRIPT_DIR/target-matrix.sh"

CORPUS_ROOT="$REPO_ROOT/asm/fixtures/gas-xref"
MANIFEST="$CORPUS_ROOT/manifest.txt"
ASM_DIR="$REPO_ROOT/asm"

Fatal() { echo "FATAL: $*" 1>&2; exit 1; }
usage() { echo "Usage: $0 --check | --regen" 1>&2; }

hash_of() { sha256sum "$1" | cut -d' ' -f1; }

# 16 bytes per line, lower case, no offset column and no duplicate-line marker.
# Byte-for-byte the format asm-fixture-oracle.sh writes, so the OCaml side reads
# both corpora with one parser.
hexdump_memory_order() {
  od -An -v -tx1 "$1" | tr -s ' ' | sed -e 's/^ //' -e 's/ $//' | awk 'NF'
}

corpus_files() {
  (cd "$CORPUS_ROOT" && find . -type f ! -name 'manifest.txt*' | sed 's|^\./||' | LC_ALL=C sort)
}

# {1 --regen}

do_regen() {
  local t
  for t in "${ALL_TARGETS[@]}"; do
    target_config "$t"
    command -v "${TOOLPREFIX}as" >/dev/null 2>&1 \
      || Fatal "${TOOLPREFIX}as not installed - the cross-reference needs the cross binutils"
  done

  # The emitter is this project's own build, so a corpus can never be
  # regenerated from an assembler that does not compile.
  rm -rf "$CORPUS_ROOT"
  mkdir -p "$CORPUS_ROOT"
  (cd "$ASM_DIR" && opam exec -- dune exec test/snippets/snippet_emit.exe -- "$CORPUS_ROOT") \
    > /dev/null

  local n=0 src
  while IFS= read -r src; do
    local dir target
    dir=$(dirname "$src")
    target=$(basename "$(dirname "$dir")")
    target_config "$target"

    # Assembled as obj.o in a scratch directory, so neither the object name nor
    # its path can reach the recorded output.
    local work
    work=$(mktemp -d)
    "${TOOLPREFIX}as" -o "$work/obj.o" "$src"
    "${TOOLPREFIX}objdump" -dr "$work/obj.o" | sed -e "s|$work/||g" -e '1,2d' > "$dir/objdump.txt"
    "${TOOLPREFIX}objcopy" --only-section=.text -O binary "$work/obj.o" "$work/text.bin"
    hexdump_memory_order "$work/text.bin" > "$dir/text.hex"
    rm -rf "$work"
    n=$((n + 1))
  done < <(find "$CORPUS_ROOT" -name input.s | LC_ALL=C sort)

  [ "$n" -gt 0 ] || Fatal "the emitter produced no cases"

  {
    for t in "${ALL_TARGETS[@]}"; do
      target_config "$t"
      printf 'as:%s\t%s\n' "$t" "$("${TOOLPREFIX}as" --version | head -1)"
      printf 'objdump:%s\t%s\n' "$t" "$("${TOOLPREFIX}objdump" --version | head -1)"
    done
  } > "$CORPUS_ROOT/tool-versions.txt"

  write_manifest
  echo "gas-xref: $n cases regenerated"
}

write_manifest() {
  local f
  {
    echo "generator	tools/asm-gas-xref.sh"
    echo "inputs	generated by asm/test/snippets/snippet_emit.ml from the AST corpus"
    while IFS= read -r f; do
      printf 'sha256:%s\t%s\n' "$f" "$(hash_of "$CORPUS_ROOT/$f")"
    done < <(corpus_files)
  } | LC_ALL=C sort > "$MANIFEST.new"
  mv "$MANIFEST.new" "$MANIFEST"
}

# {1 --check}
#
# Identical in mechanism to asm-fixture-gen.sh --check, including the
# UNRECORDED rule: a file present in the tree but absent from the manifest is
# just as much a divergence as a changed one, because it would otherwise ride
# along unreviewed.

do_check() {
  [ -f "$MANIFEST" ] || Fatal "no manifest at $MANIFEST - run --regen first"
  local rc=0 seen=0 key value path f
  while IFS=$'\t' read -r key value; do
    case "$key" in
      sha256:*)
        path=${key#sha256:}
        seen=$((seen + 1))
        if [ ! -f "$CORPUS_ROOT/$path" ]; then
          echo "MISSING $path" >&2; rc=1
        elif [ "$(hash_of "$CORPUS_ROOT/$path")" != "$value" ]; then
          echo "CHANGED $path" >&2; rc=1
        fi
        ;;
    esac
  done < "$MANIFEST"

  # A file present in the tree but absent from the manifest is just as much a
  # divergence as a changed one: it would otherwise ride along unreviewed.
  local present=0
  while IFS= read -r f; do
    present=$((present + 1))
    grep -q "^sha256:$f	" "$MANIFEST" || { echo "UNRECORDED $f" >&2; rc=1; }
  done < <(corpus_files)

  # The scan above runs in a process substitution, where a failure would not
  # reach `set -e` - the loop would simply not execute and --check would pass
  # having compared nothing in that direction. Counting is what makes the
  # difference between "no unrecorded files" and "the scan did not run".
  [ "$present" -gt 0 ] || Fatal "found no files under $CORPUS_ROOT"
  [ "$seen" -gt 0 ] || Fatal "manifest records no files"
  [ "$rc" -eq 0 ] && echo "gas-xref: $seen files match the manifest"
  return "$rc"
}

case "${1:-}" in
  --check) do_check ;;
  --regen) do_regen ;;
  *) usage; exit 2 ;;
esac
