(* Generated by [compcert_tools isa-table riscv-emit] from the committed riscv-opcodes
   exports (isa-db/export/riscv_opcodes); do not edit by hand. The selection and field
   domains are Isa_riscv_table's DEC-RV-TABLE rule. *)

open Riscv_table_row

let rows : row array =
  [|
    {
      mnemonic = "sspopchk";
      mask = 0xffffffffL;
      match_ = 0xcdc0c073L;
      operands = [ Fixed_gpr 1 ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/sspopchk.x1";
    };
    {
      mnemonic = "sspopchk";
      mask = 0xffffffffL;
      match_ = 0xcdc2c073L;
      operands = [ Fixed_gpr 5 ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/sspopchk.x5";
    };
    {
      mnemonic = "sspush";
      mask = 0xffffffffL;
      match_ = 0xce104073L;
      operands = [ Fixed_gpr 1 ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/sspush.x1";
    };
    {
      mnemonic = "sspush";
      mask = 0xffffffffL;
      match_ = 0xce504073L;
      operands = [ Fixed_gpr 5 ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/sspush.x5";
    };
    {
      mnemonic = "frcsr";
      mask = 0xfffff07fL;
      match_ = 0x302073L;
      operands = [ Gpr { lsb = 7; nonzero = false } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/frcsr";
    };
    {
      mnemonic = "frflags";
      mask = 0xfffff07fL;
      match_ = 0x102073L;
      operands = [ Gpr { lsb = 7; nonzero = false } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/frflags";
    };
    {
      mnemonic = "frrm";
      mask = 0xfffff07fL;
      match_ = 0x202073L;
      operands = [ Gpr { lsb = 7; nonzero = false } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/frrm";
    };
    {
      mnemonic = "ssrdp";
      mask = 0xfffff07fL;
      match_ = 0xcdc04073L;
      operands = [ Gpr { lsb = 7; nonzero = true } ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/ssrdp";
    };
    {
      mnemonic = "fmv.d.x";
      mask = 0xfff0707fL;
      match_ = 0xf2000053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 64;
      feature = "d";
      source = "rv64_d/fmv.d.x";
    };
    {
      mnemonic = "zext.w";
      mask = 0xfff0707fL;
      match_ = 0x800003bL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 64;
      feature = "zba";
      source = "rv64_zba/zext.w";
    };
    {
      mnemonic = "fscsr";
      mask = 0xfff0707fL;
      match_ = 0x301073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/fscsr";
    };
    {
      mnemonic = "fsflags";
      mask = 0xfff0707fL;
      match_ = 0x101073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/fsflags";
    };
    {
      mnemonic = "fsflagsi";
      mask = 0xfff0707fL;
      match_ = 0x105073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Uimm { lsb = 15; width = 5 } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/fsflagsi";
    };
    {
      mnemonic = "fsrm";
      mask = 0xfff0707fL;
      match_ = 0x201073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/fsrm";
    };
    {
      mnemonic = "fsrmi";
      mask = 0xfff0707fL;
      match_ = 0x205073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Uimm { lsb = 15; width = 5 } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/fsrmi";
    };
    {
      mnemonic = "mop.r.0";
      mask = 0xfff0707fL;
      match_ = 0x81c04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.0";
    };
    {
      mnemonic = "mop.r.10";
      mask = 0xfff0707fL;
      match_ = 0x89e04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.10";
    };
    {
      mnemonic = "mop.r.11";
      mask = 0xfff0707fL;
      match_ = 0x89f04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.11";
    };
    {
      mnemonic = "mop.r.12";
      mask = 0xfff0707fL;
      match_ = 0x8dc04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.12";
    };
    {
      mnemonic = "mop.r.13";
      mask = 0xfff0707fL;
      match_ = 0x8dd04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.13";
    };
    {
      mnemonic = "mop.r.14";
      mask = 0xfff0707fL;
      match_ = 0x8de04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.14";
    };
    {
      mnemonic = "mop.r.15";
      mask = 0xfff0707fL;
      match_ = 0x8df04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.15";
    };
    {
      mnemonic = "mop.r.16";
      mask = 0xfff0707fL;
      match_ = 0xc1c04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.16";
    };
    {
      mnemonic = "mop.r.17";
      mask = 0xfff0707fL;
      match_ = 0xc1d04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.17";
    };
    {
      mnemonic = "mop.r.18";
      mask = 0xfff0707fL;
      match_ = 0xc1e04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.18";
    };
    {
      mnemonic = "mop.r.19";
      mask = 0xfff0707fL;
      match_ = 0xc1f04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.19";
    };
    {
      mnemonic = "mop.r.1";
      mask = 0xfff0707fL;
      match_ = 0x81d04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.1";
    };
    {
      mnemonic = "mop.r.20";
      mask = 0xfff0707fL;
      match_ = 0xc5c04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.20";
    };
    {
      mnemonic = "mop.r.21";
      mask = 0xfff0707fL;
      match_ = 0xc5d04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.21";
    };
    {
      mnemonic = "mop.r.22";
      mask = 0xfff0707fL;
      match_ = 0xc5e04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.22";
    };
    {
      mnemonic = "mop.r.23";
      mask = 0xfff0707fL;
      match_ = 0xc5f04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.23";
    };
    {
      mnemonic = "mop.r.24";
      mask = 0xfff0707fL;
      match_ = 0xc9c04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.24";
    };
    {
      mnemonic = "mop.r.25";
      mask = 0xfff0707fL;
      match_ = 0xc9d04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.25";
    };
    {
      mnemonic = "mop.r.26";
      mask = 0xfff0707fL;
      match_ = 0xc9e04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.26";
    };
    {
      mnemonic = "mop.r.27";
      mask = 0xfff0707fL;
      match_ = 0xc9f04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.27";
    };
    {
      mnemonic = "mop.r.28";
      mask = 0xfff0707fL;
      match_ = 0xcdc04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.28";
    };
    {
      mnemonic = "mop.r.29";
      mask = 0xfff0707fL;
      match_ = 0xcdd04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.29";
    };
    {
      mnemonic = "mop.r.2";
      mask = 0xfff0707fL;
      match_ = 0x81e04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.2";
    };
    {
      mnemonic = "mop.r.30";
      mask = 0xfff0707fL;
      match_ = 0xcde04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.30";
    };
    {
      mnemonic = "mop.r.31";
      mask = 0xfff0707fL;
      match_ = 0xcdf04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.31";
    };
    {
      mnemonic = "mop.r.3";
      mask = 0xfff0707fL;
      match_ = 0x81f04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.3";
    };
    {
      mnemonic = "mop.r.4";
      mask = 0xfff0707fL;
      match_ = 0x85c04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.4";
    };
    {
      mnemonic = "mop.r.5";
      mask = 0xfff0707fL;
      match_ = 0x85d04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.5";
    };
    {
      mnemonic = "mop.r.6";
      mask = 0xfff0707fL;
      match_ = 0x85e04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.6";
    };
    {
      mnemonic = "mop.r.7";
      mask = 0xfff0707fL;
      match_ = 0x85f04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.7";
    };
    {
      mnemonic = "mop.r.8";
      mask = 0xfff0707fL;
      match_ = 0x89c04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.8";
    };
    {
      mnemonic = "mop.r.9";
      mask = 0xfff0707fL;
      match_ = 0x89d04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.9";
    };
    {
      mnemonic = "add.uw";
      mask = 0xfe00707fL;
      match_ = 0x800003bL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 64;
      feature = "zba";
      source = "rv64_zba/add.uw";
    };
    {
      mnemonic = "mop.rr.0";
      mask = 0xfe00707fL;
      match_ = 0x82004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.0";
    };
    {
      mnemonic = "mop.rr.1";
      mask = 0xfe00707fL;
      match_ = 0x86004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.1";
    };
    {
      mnemonic = "mop.rr.2";
      mask = 0xfe00707fL;
      match_ = 0x8a004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.2";
    };
    {
      mnemonic = "mop.rr.3";
      mask = 0xfe00707fL;
      match_ = 0x8e004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.3";
    };
    {
      mnemonic = "mop.rr.4";
      mask = 0xfe00707fL;
      match_ = 0xc2004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.4";
    };
    {
      mnemonic = "mop.rr.5";
      mask = 0xfe00707fL;
      match_ = 0xc6004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.5";
    };
    {
      mnemonic = "mop.rr.6";
      mask = 0xfe00707fL;
      match_ = 0xca004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.6";
    };
    {
      mnemonic = "mop.rr.7";
      mask = 0xfe00707fL;
      match_ = 0xce004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.7";
    };
    {
      mnemonic = "slli.uw";
      mask = 0xfc00707fL;
      match_ = 0x800101bL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Uimm { lsb = 20; width = 6 } ];
      xlen = 64;
      feature = "zba";
      source = "rv64_zba/slli.uw";
    };
  |]
