(* Generated by [compcert_tools isa-table riscv-emit] from the committed riscv-opcodes
   exports (isa-db/export/riscv_opcodes); do not edit by hand. The selection and field
   domains are Isa_riscv_table's DEC-RV-TABLE rule. *)

open Riscv_table_row

let rows : row array =
  [|
    {
      mnemonic = "sspopchk";
      mask = 0xffffffffL;
      match_ = 0xcdc0c073L;
      operands = [ Fixed_gpr 1 ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/sspopchk.x1";
    };
    {
      mnemonic = "sspopchk";
      mask = 0xffffffffL;
      match_ = 0xcdc2c073L;
      operands = [ Fixed_gpr 5 ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/sspopchk.x5";
    };
    {
      mnemonic = "sspush";
      mask = 0xffffffffL;
      match_ = 0xce104073L;
      operands = [ Fixed_gpr 1 ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/sspush.x1";
    };
    {
      mnemonic = "sspush";
      mask = 0xffffffffL;
      match_ = 0xce504073L;
      operands = [ Fixed_gpr 5 ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/sspush.x5";
    };
    {
      mnemonic = "frcsr";
      mask = 0xfffff07fL;
      match_ = 0x302073L;
      operands = [ Gpr { lsb = 7; nonzero = false } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/frcsr";
    };
    {
      mnemonic = "frflags";
      mask = 0xfffff07fL;
      match_ = 0x102073L;
      operands = [ Gpr { lsb = 7; nonzero = false } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/frflags";
    };
    {
      mnemonic = "frrm";
      mask = 0xfffff07fL;
      match_ = 0x202073L;
      operands = [ Gpr { lsb = 7; nonzero = false } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/frrm";
    };
    {
      mnemonic = "ssrdp";
      mask = 0xfffff07fL;
      match_ = 0xcdc04073L;
      operands = [ Gpr { lsb = 7; nonzero = true } ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/ssrdp";
    };
    {
      mnemonic = "fmv.d.x";
      mask = 0xfff0707fL;
      match_ = 0xf2000053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 64;
      feature = "d";
      source = "rv64_d/fmv.d.x";
    };
    {
      mnemonic = "fmvh.x.q";
      mask = 0xfff0707fL;
      match_ = 0xe6100053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 } ];
      xlen = 64;
      feature = "zfa";
      source = "rv64_q_zfa/fmvh.x.q";
    };
    {
      mnemonic = "zext.w";
      mask = 0xfff0707fL;
      match_ = 0x800003bL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 64;
      feature = "zba";
      source = "rv64_zba/zext.w";
    };
    {
      mnemonic = "fcvtmod.w.d";
      mask = 0xfff0707fL;
      match_ = 0xc2801053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Keyword "rtz" ];
      xlen = 0;
      feature = "zfa";
      source = "rv_d_zfa/fcvtmod.w.d";
    };
    {
      mnemonic = "fli.d";
      mask = 0xfff0707fL;
      match_ = 0xf2100053L;
      operands = [ Fpr { lsb = 7 }; Fli { lsb = 15 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_d_zfa/fli.d";
    };
    {
      mnemonic = "fscsr";
      mask = 0xfff0707fL;
      match_ = 0x301073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/fscsr";
    };
    {
      mnemonic = "fsflags";
      mask = 0xfff0707fL;
      match_ = 0x101073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/fsflags";
    };
    {
      mnemonic = "fsflagsi";
      mask = 0xfff0707fL;
      match_ = 0x105073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Uimm { lsb = 15; width = 5 } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/fsflagsi";
    };
    {
      mnemonic = "fsrm";
      mask = 0xfff0707fL;
      match_ = 0x201073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/fsrm";
    };
    {
      mnemonic = "fsrmi";
      mask = 0xfff0707fL;
      match_ = 0x205073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Uimm { lsb = 15; width = 5 } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/fsrmi";
    };
    {
      mnemonic = "fli.s";
      mask = 0xfff0707fL;
      match_ = 0xf0100053L;
      operands = [ Fpr { lsb = 7 }; Fli { lsb = 15 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_f_zfa/fli.s";
    };
    {
      mnemonic = "fclass.q";
      mask = 0xfff0707fL;
      match_ = 0xe6001053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fclass.q";
    };
    {
      mnemonic = "fli.q";
      mask = 0xfff0707fL;
      match_ = 0xf6100053L;
      operands = [ Fpr { lsb = 7 }; Fli { lsb = 15 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_q_zfa/fli.q";
    };
    {
      mnemonic = "fclass.h";
      mask = 0xfff0707fL;
      match_ = 0xe4001053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fclass.h";
    };
    {
      mnemonic = "fli.h";
      mask = 0xfff0707fL;
      match_ = 0xf4100053L;
      operands = [ Fpr { lsb = 7 }; Fli { lsb = 15 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_zfh_zfa/fli.h";
    };
    {
      mnemonic = "fmv.h.x";
      mask = 0xfff0707fL;
      match_ = 0xf4000053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zfhmin";
      source = "rv_zfhmin/fmv.h.x";
    };
    {
      mnemonic = "fmv.x.h";
      mask = 0xfff0707fL;
      match_ = 0xe4000053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 } ];
      xlen = 0;
      feature = "zfhmin";
      source = "rv_zfhmin/fmv.x.h";
    };
    {
      mnemonic = "mop.r.0";
      mask = 0xfff0707fL;
      match_ = 0x81c04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.0";
    };
    {
      mnemonic = "mop.r.10";
      mask = 0xfff0707fL;
      match_ = 0x89e04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.10";
    };
    {
      mnemonic = "mop.r.11";
      mask = 0xfff0707fL;
      match_ = 0x89f04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.11";
    };
    {
      mnemonic = "mop.r.12";
      mask = 0xfff0707fL;
      match_ = 0x8dc04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.12";
    };
    {
      mnemonic = "mop.r.13";
      mask = 0xfff0707fL;
      match_ = 0x8dd04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.13";
    };
    {
      mnemonic = "mop.r.14";
      mask = 0xfff0707fL;
      match_ = 0x8de04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.14";
    };
    {
      mnemonic = "mop.r.15";
      mask = 0xfff0707fL;
      match_ = 0x8df04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.15";
    };
    {
      mnemonic = "mop.r.16";
      mask = 0xfff0707fL;
      match_ = 0xc1c04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.16";
    };
    {
      mnemonic = "mop.r.17";
      mask = 0xfff0707fL;
      match_ = 0xc1d04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.17";
    };
    {
      mnemonic = "mop.r.18";
      mask = 0xfff0707fL;
      match_ = 0xc1e04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.18";
    };
    {
      mnemonic = "mop.r.19";
      mask = 0xfff0707fL;
      match_ = 0xc1f04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.19";
    };
    {
      mnemonic = "mop.r.1";
      mask = 0xfff0707fL;
      match_ = 0x81d04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.1";
    };
    {
      mnemonic = "mop.r.20";
      mask = 0xfff0707fL;
      match_ = 0xc5c04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.20";
    };
    {
      mnemonic = "mop.r.21";
      mask = 0xfff0707fL;
      match_ = 0xc5d04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.21";
    };
    {
      mnemonic = "mop.r.22";
      mask = 0xfff0707fL;
      match_ = 0xc5e04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.22";
    };
    {
      mnemonic = "mop.r.23";
      mask = 0xfff0707fL;
      match_ = 0xc5f04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.23";
    };
    {
      mnemonic = "mop.r.24";
      mask = 0xfff0707fL;
      match_ = 0xc9c04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.24";
    };
    {
      mnemonic = "mop.r.25";
      mask = 0xfff0707fL;
      match_ = 0xc9d04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.25";
    };
    {
      mnemonic = "mop.r.26";
      mask = 0xfff0707fL;
      match_ = 0xc9e04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.26";
    };
    {
      mnemonic = "mop.r.27";
      mask = 0xfff0707fL;
      match_ = 0xc9f04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.27";
    };
    {
      mnemonic = "mop.r.28";
      mask = 0xfff0707fL;
      match_ = 0xcdc04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.28";
    };
    {
      mnemonic = "mop.r.29";
      mask = 0xfff0707fL;
      match_ = 0xcdd04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.29";
    };
    {
      mnemonic = "mop.r.2";
      mask = 0xfff0707fL;
      match_ = 0x81e04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.2";
    };
    {
      mnemonic = "mop.r.30";
      mask = 0xfff0707fL;
      match_ = 0xcde04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.30";
    };
    {
      mnemonic = "mop.r.31";
      mask = 0xfff0707fL;
      match_ = 0xcdf04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.31";
    };
    {
      mnemonic = "mop.r.3";
      mask = 0xfff0707fL;
      match_ = 0x81f04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.3";
    };
    {
      mnemonic = "mop.r.4";
      mask = 0xfff0707fL;
      match_ = 0x85c04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.4";
    };
    {
      mnemonic = "mop.r.5";
      mask = 0xfff0707fL;
      match_ = 0x85d04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.5";
    };
    {
      mnemonic = "mop.r.6";
      mask = 0xfff0707fL;
      match_ = 0x85e04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.6";
    };
    {
      mnemonic = "mop.r.7";
      mask = 0xfff0707fL;
      match_ = 0x85f04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.7";
    };
    {
      mnemonic = "mop.r.8";
      mask = 0xfff0707fL;
      match_ = 0x89c04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.8";
    };
    {
      mnemonic = "mop.r.9";
      mask = 0xfff0707fL;
      match_ = 0x89d04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.9";
    };
    {
      mnemonic = "fmvh.x.d";
      mask = 0xfff0707fL;
      match_ = 0xe2100053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 } ];
      xlen = 32;
      feature = "zfa";
      source = "rv32_d_zfa/fmvh.x.d";
    };
    {
      mnemonic = "fcvt.l.q";
      mask = 0xfff0007fL;
      match_ = 0xc6200053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 64;
      feature = "q";
      source = "rv64_q/fcvt.l.q";
    };
    {
      mnemonic = "fcvt.lu.q";
      mask = 0xfff0007fL;
      match_ = 0xc6300053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 64;
      feature = "q";
      source = "rv64_q/fcvt.lu.q";
    };
    {
      mnemonic = "fcvt.q.l";
      mask = 0xfff0007fL;
      match_ = 0xd6200053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false }; Rm { lsb = 12; default = 0 } ];
      xlen = 64;
      feature = "q";
      source = "rv64_q/fcvt.q.l";
    };
    {
      mnemonic = "fcvt.q.lu";
      mask = 0xfff0007fL;
      match_ = 0xd6300053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false }; Rm { lsb = 12; default = 0 } ];
      xlen = 64;
      feature = "q";
      source = "rv64_q/fcvt.q.lu";
    };
    {
      mnemonic = "fcvt.h.l";
      mask = 0xfff0007fL;
      match_ = 0xd4200053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false }; Rm { lsb = 12; default = 7 } ];
      xlen = 64;
      feature = "zfh";
      source = "rv64_zfh/fcvt.h.l";
    };
    {
      mnemonic = "fcvt.h.lu";
      mask = 0xfff0007fL;
      match_ = 0xd4300053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false }; Rm { lsb = 12; default = 7 } ];
      xlen = 64;
      feature = "zfh";
      source = "rv64_zfh/fcvt.h.lu";
    };
    {
      mnemonic = "fcvt.l.h";
      mask = 0xfff0007fL;
      match_ = 0xc4200053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 64;
      feature = "zfh";
      source = "rv64_zfh/fcvt.l.h";
    };
    {
      mnemonic = "fcvt.lu.h";
      mask = 0xfff0007fL;
      match_ = 0xc4300053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 64;
      feature = "zfh";
      source = "rv64_zfh/fcvt.lu.h";
    };
    {
      mnemonic = "fround.d";
      mask = 0xfff0007fL;
      match_ = 0x42400053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_d_zfa/fround.d";
    };
    {
      mnemonic = "froundnx.d";
      mask = 0xfff0007fL;
      match_ = 0x42500053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_d_zfa/froundnx.d";
    };
    {
      mnemonic = "fcvt.d.h";
      mask = 0xfff0007fL;
      match_ = 0x42200053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 0 } ];
      xlen = 0;
      feature = "zfhmin";
      source = "rv_d_zfhmin/fcvt.d.h";
    };
    {
      mnemonic = "fcvt.h.d";
      mask = 0xfff0007fL;
      match_ = 0x44100053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfhmin";
      source = "rv_d_zfhmin/fcvt.h.d";
    };
    {
      mnemonic = "fround.s";
      mask = 0xfff0007fL;
      match_ = 0x40400053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_f_zfa/fround.s";
    };
    {
      mnemonic = "froundnx.s";
      mask = 0xfff0007fL;
      match_ = 0x40500053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_f_zfa/froundnx.s";
    };
    {
      mnemonic = "fcvt.d.q";
      mask = 0xfff0007fL;
      match_ = 0x42300053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fcvt.d.q";
    };
    {
      mnemonic = "fcvt.q.d";
      mask = 0xfff0007fL;
      match_ = 0x46100053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 0 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fcvt.q.d";
    };
    {
      mnemonic = "fcvt.q.s";
      mask = 0xfff0007fL;
      match_ = 0x46000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 0 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fcvt.q.s";
    };
    {
      mnemonic = "fcvt.q.w";
      mask = 0xfff0007fL;
      match_ = 0xd6000053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false }; Rm { lsb = 12; default = 0 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fcvt.q.w";
    };
    {
      mnemonic = "fcvt.q.wu";
      mask = 0xfff0007fL;
      match_ = 0xd6100053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false }; Rm { lsb = 12; default = 0 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fcvt.q.wu";
    };
    {
      mnemonic = "fcvt.s.q";
      mask = 0xfff0007fL;
      match_ = 0x40300053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fcvt.s.q";
    };
    {
      mnemonic = "fcvt.w.q";
      mask = 0xfff0007fL;
      match_ = 0xc6000053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fcvt.w.q";
    };
    {
      mnemonic = "fcvt.wu.q";
      mask = 0xfff0007fL;
      match_ = 0xc6100053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fcvt.wu.q";
    };
    {
      mnemonic = "fsqrt.q";
      mask = 0xfff0007fL;
      match_ = 0x5e000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fsqrt.q";
    };
    {
      mnemonic = "fround.q";
      mask = 0xfff0007fL;
      match_ = 0x46400053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_q_zfa/fround.q";
    };
    {
      mnemonic = "froundnx.q";
      mask = 0xfff0007fL;
      match_ = 0x46500053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_q_zfa/froundnx.q";
    };
    {
      mnemonic = "fcvt.h.q";
      mask = 0xfff0007fL;
      match_ = 0x44300053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfhmin";
      source = "rv_q_zfhmin/fcvt.h.q";
    };
    {
      mnemonic = "fcvt.q.h";
      mask = 0xfff0007fL;
      match_ = 0x46200053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 0 } ];
      xlen = 0;
      feature = "zfhmin";
      source = "rv_q_zfhmin/fcvt.q.h";
    };
    {
      mnemonic = "fcvt.bf16.s";
      mask = 0xfff0007fL;
      match_ = 0x44800053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfbfmin";
      source = "rv_zfbfmin/fcvt.bf16.s";
    };
    {
      mnemonic = "fcvt.s.bf16";
      mask = 0xfff0007fL;
      match_ = 0x40600053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 0 } ];
      xlen = 0;
      feature = "zfbfmin";
      source = "rv_zfbfmin/fcvt.s.bf16";
    };
    {
      mnemonic = "fcvt.h.w";
      mask = 0xfff0007fL;
      match_ = 0xd4000053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fcvt.h.w";
    };
    {
      mnemonic = "fcvt.h.wu";
      mask = 0xfff0007fL;
      match_ = 0xd4100053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fcvt.h.wu";
    };
    {
      mnemonic = "fcvt.w.h";
      mask = 0xfff0007fL;
      match_ = 0xc4000053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fcvt.w.h";
    };
    {
      mnemonic = "fcvt.wu.h";
      mask = 0xfff0007fL;
      match_ = 0xc4100053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fcvt.wu.h";
    };
    {
      mnemonic = "fsqrt.h";
      mask = 0xfff0007fL;
      match_ = 0x5c000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fsqrt.h";
    };
    {
      mnemonic = "fround.h";
      mask = 0xfff0007fL;
      match_ = 0x44400053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_zfh_zfa/fround.h";
    };
    {
      mnemonic = "froundnx.h";
      mask = 0xfff0007fL;
      match_ = 0x44500053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_zfh_zfa/froundnx.h";
    };
    {
      mnemonic = "fcvt.h.s";
      mask = 0xfff0007fL;
      match_ = 0x44000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfhmin";
      source = "rv_zfhmin/fcvt.h.s";
    };
    {
      mnemonic = "fcvt.s.h";
      mask = 0xfff0007fL;
      match_ = 0x40200053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 0 } ];
      xlen = 0;
      feature = "zfhmin";
      source = "rv_zfhmin/fcvt.s.h";
    };
    {
      mnemonic = "fabs.q";
      mask = 0xfe00707fL;
      match_ = 0x26002053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Tied { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fabs.q";
    };
    {
      mnemonic = "fmv.q";
      mask = 0xfe00707fL;
      match_ = 0x26000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Tied { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fmv.q";
    };
    {
      mnemonic = "fneg.q";
      mask = 0xfe00707fL;
      match_ = 0x26001053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Tied { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fneg.q";
    };
    {
      mnemonic = "fabs.h";
      mask = 0xfe00707fL;
      match_ = 0x24002053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Tied { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fabs.h";
    };
    {
      mnemonic = "fmv.h";
      mask = 0xfe00707fL;
      match_ = 0x24000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Tied { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fmv.h";
    };
    {
      mnemonic = "fneg.h";
      mask = 0xfe00707fL;
      match_ = 0x24001053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Tied { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fneg.h";
    };
    {
      mnemonic = "fmvp.q.x";
      mask = 0xfe00707fL;
      match_ = 0xb6000053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 64;
      feature = "zfa";
      source = "rv64_q_zfa/fmvp.q.x";
    };
    {
      mnemonic = "add.uw";
      mask = 0xfe00707fL;
      match_ = 0x800003bL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 64;
      feature = "zba";
      source = "rv64_zba/add.uw";
    };
    {
      mnemonic = "fleq.d";
      mask = 0xfe00707fL;
      match_ = 0xa2004053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_d_zfa/fleq.d";
    };
    {
      mnemonic = "fltq.d";
      mask = 0xfe00707fL;
      match_ = 0xa2005053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_d_zfa/fltq.d";
    };
    {
      mnemonic = "fmaxm.d";
      mask = 0xfe00707fL;
      match_ = 0x2a003053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_d_zfa/fmaxm.d";
    };
    {
      mnemonic = "fminm.d";
      mask = 0xfe00707fL;
      match_ = 0x2a002053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_d_zfa/fminm.d";
    };
    {
      mnemonic = "fleq.s";
      mask = 0xfe00707fL;
      match_ = 0xa0004053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_f_zfa/fleq.s";
    };
    {
      mnemonic = "fltq.s";
      mask = 0xfe00707fL;
      match_ = 0xa0005053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_f_zfa/fltq.s";
    };
    {
      mnemonic = "fmaxm.s";
      mask = 0xfe00707fL;
      match_ = 0x28003053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_f_zfa/fmaxm.s";
    };
    {
      mnemonic = "fminm.s";
      mask = 0xfe00707fL;
      match_ = 0x28002053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_f_zfa/fminm.s";
    };
    {
      mnemonic = "feq.q";
      mask = 0xfe00707fL;
      match_ = 0xa6002053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/feq.q";
    };
    {
      mnemonic = "fle.q";
      mask = 0xfe00707fL;
      match_ = 0xa6000053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fle.q";
    };
    {
      mnemonic = "flt.q";
      mask = 0xfe00707fL;
      match_ = 0xa6001053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/flt.q";
    };
    {
      mnemonic = "fmax.q";
      mask = 0xfe00707fL;
      match_ = 0x2e001053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fmax.q";
    };
    {
      mnemonic = "fmin.q";
      mask = 0xfe00707fL;
      match_ = 0x2e000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fmin.q";
    };
    {
      mnemonic = "fsgnj.q";
      mask = 0xfe00707fL;
      match_ = 0x26000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fsgnj.q";
    };
    {
      mnemonic = "fsgnjn.q";
      mask = 0xfe00707fL;
      match_ = 0x26001053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fsgnjn.q";
    };
    {
      mnemonic = "fsgnjx.q";
      mask = 0xfe00707fL;
      match_ = 0x26002053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fsgnjx.q";
    };
    {
      mnemonic = "fleq.q";
      mask = 0xfe00707fL;
      match_ = 0xa6004053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_q_zfa/fleq.q";
    };
    {
      mnemonic = "fltq.q";
      mask = 0xfe00707fL;
      match_ = 0xa6005053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_q_zfa/fltq.q";
    };
    {
      mnemonic = "fmaxm.q";
      mask = 0xfe00707fL;
      match_ = 0x2e003053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_q_zfa/fmaxm.q";
    };
    {
      mnemonic = "fminm.q";
      mask = 0xfe00707fL;
      match_ = 0x2e002053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_q_zfa/fminm.q";
    };
    {
      mnemonic = "feq.h";
      mask = 0xfe00707fL;
      match_ = 0xa4002053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/feq.h";
    };
    {
      mnemonic = "fle.h";
      mask = 0xfe00707fL;
      match_ = 0xa4000053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fle.h";
    };
    {
      mnemonic = "flt.h";
      mask = 0xfe00707fL;
      match_ = 0xa4001053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/flt.h";
    };
    {
      mnemonic = "fmax.h";
      mask = 0xfe00707fL;
      match_ = 0x2c001053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fmax.h";
    };
    {
      mnemonic = "fmin.h";
      mask = 0xfe00707fL;
      match_ = 0x2c000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fmin.h";
    };
    {
      mnemonic = "fsgnj.h";
      mask = 0xfe00707fL;
      match_ = 0x24000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fsgnj.h";
    };
    {
      mnemonic = "fsgnjn.h";
      mask = 0xfe00707fL;
      match_ = 0x24001053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fsgnjn.h";
    };
    {
      mnemonic = "fsgnjx.h";
      mask = 0xfe00707fL;
      match_ = 0x24002053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fsgnjx.h";
    };
    {
      mnemonic = "fleq.h";
      mask = 0xfe00707fL;
      match_ = 0xa4004053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_zfh_zfa/fleq.h";
    };
    {
      mnemonic = "fltq.h";
      mask = 0xfe00707fL;
      match_ = 0xa4005053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_zfh_zfa/fltq.h";
    };
    {
      mnemonic = "fmaxm.h";
      mask = 0xfe00707fL;
      match_ = 0x2c003053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_zfh_zfa/fmaxm.h";
    };
    {
      mnemonic = "fminm.h";
      mask = 0xfe00707fL;
      match_ = 0x2c002053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_zfh_zfa/fminm.h";
    };
    {
      mnemonic = "mop.rr.0";
      mask = 0xfe00707fL;
      match_ = 0x82004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.0";
    };
    {
      mnemonic = "mop.rr.1";
      mask = 0xfe00707fL;
      match_ = 0x86004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.1";
    };
    {
      mnemonic = "mop.rr.2";
      mask = 0xfe00707fL;
      match_ = 0x8a004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.2";
    };
    {
      mnemonic = "mop.rr.3";
      mask = 0xfe00707fL;
      match_ = 0x8e004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.3";
    };
    {
      mnemonic = "mop.rr.4";
      mask = 0xfe00707fL;
      match_ = 0xc2004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.4";
    };
    {
      mnemonic = "mop.rr.5";
      mask = 0xfe00707fL;
      match_ = 0xc6004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.5";
    };
    {
      mnemonic = "mop.rr.6";
      mask = 0xfe00707fL;
      match_ = 0xca004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.6";
    };
    {
      mnemonic = "mop.rr.7";
      mask = 0xfe00707fL;
      match_ = 0xce004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.7";
    };
    {
      mnemonic = "fmvp.d.x";
      mask = 0xfe00707fL;
      match_ = 0xb2000053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 32;
      feature = "zfa";
      source = "rv32_d_zfa/fmvp.d.x";
    };
    {
      mnemonic = "slli.uw";
      mask = 0xfc00707fL;
      match_ = 0x800101bL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Uimm { lsb = 20; width = 6 } ];
      xlen = 64;
      feature = "zba";
      source = "rv64_zba/slli.uw";
    };
    {
      mnemonic = "fadd.q";
      mask = 0xfe00007fL;
      match_ = 0x6000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fadd.q";
    };
    {
      mnemonic = "fdiv.q";
      mask = 0xfe00007fL;
      match_ = 0x1e000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fdiv.q";
    };
    {
      mnemonic = "fmul.q";
      mask = 0xfe00007fL;
      match_ = 0x16000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fmul.q";
    };
    {
      mnemonic = "fsub.q";
      mask = 0xfe00007fL;
      match_ = 0xe000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fsub.q";
    };
    {
      mnemonic = "fadd.h";
      mask = 0xfe00007fL;
      match_ = 0x4000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fadd.h";
    };
    {
      mnemonic = "fdiv.h";
      mask = 0xfe00007fL;
      match_ = 0x1c000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fdiv.h";
    };
    {
      mnemonic = "fmul.h";
      mask = 0xfe00007fL;
      match_ = 0x14000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fmul.h";
    };
    {
      mnemonic = "fsub.h";
      mask = 0xfe00007fL;
      match_ = 0xc000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fsub.h";
    };
    {
      mnemonic = "flq";
      mask = 0x707fL;
      match_ = 0x4007L;
      operands = [ Fpr { lsb = 7 }; Mem_i { base = 15 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/flq";
    };
    {
      mnemonic = "fsq";
      mask = 0x707fL;
      match_ = 0x4027L;
      operands = [ Fpr { lsb = 20 }; Mem_s { base = 15 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fsq";
    };
    {
      mnemonic = "flh";
      mask = 0x707fL;
      match_ = 0x1007L;
      operands = [ Fpr { lsb = 7 }; Mem_i { base = 15 } ];
      xlen = 0;
      feature = "zfhmin";
      source = "rv_zfhmin/flh";
    };
    {
      mnemonic = "fsh";
      mask = 0x707fL;
      match_ = 0x1027L;
      operands = [ Fpr { lsb = 20 }; Mem_s { base = 15 } ];
      xlen = 0;
      feature = "zfhmin";
      source = "rv_zfhmin/fsh";
    };
    {
      mnemonic = "fmadd.q";
      mask = 0x600007fL;
      match_ = 0x6000043L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Fpr { lsb = 27 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fmadd.q";
    };
    {
      mnemonic = "fmsub.q";
      mask = 0x600007fL;
      match_ = 0x6000047L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Fpr { lsb = 27 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fmsub.q";
    };
    {
      mnemonic = "fnmadd.q";
      mask = 0x600007fL;
      match_ = 0x600004fL;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Fpr { lsb = 27 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fnmadd.q";
    };
    {
      mnemonic = "fnmsub.q";
      mask = 0x600007fL;
      match_ = 0x600004bL;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Fpr { lsb = 27 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fnmsub.q";
    };
    {
      mnemonic = "fmadd.h";
      mask = 0x600007fL;
      match_ = 0x4000043L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Fpr { lsb = 27 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fmadd.h";
    };
    {
      mnemonic = "fmsub.h";
      mask = 0x600007fL;
      match_ = 0x4000047L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Fpr { lsb = 27 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fmsub.h";
    };
    {
      mnemonic = "fnmadd.h";
      mask = 0x600007fL;
      match_ = 0x400004fL;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Fpr { lsb = 27 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fnmadd.h";
    };
    {
      mnemonic = "fnmsub.h";
      mask = 0x600007fL;
      match_ = 0x400004bL;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Fpr { lsb = 27 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fnmsub.h";
    };
  |]
